### ISSUE TITLE
segfaulting on Python 3.8

### ISSUE THREAD

**Issue by untitaker** [getsentry/ingest-load-tester#16]
The load tester is segfaulting on Python 3.8. The workaround is to manually upgrade greenlet and gevent to the latest version. This creates a version conflict with locustio which appears to be negligible.

We should upgrade locust to fix this.

**Comment by RaduW** [comment]
Thanks @untitaker, we just upgraded Locust (and removed python 3.6 pinning), also removed the manual dependency on greenlet
